### ISSUE TITLE
Dashboard: Use MD color palette

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#245] opened 2016-09-14 18:37 UTC
Use the MD color palette for the dashboard, including graphs. @cjenkins-rti might advise on this.

**Comment by scloo** [comment] 2016-09-15 20:27
Duplicate of 236

**Comment by gmcressman** [comment] 2016-09-25 18:44
Duplicate of #236.

**Closed** 2016-09-25 18:45 UTC
Labels: blocker, enhancement
